[tool.poetry]
name = "spenv"
version = "0.1.0"
description = "Spectral Envelope for Python"
authors = ["João Pedro Saraiva"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
